chore: gitignore

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,30 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
-npm run lint && npm run test
+npm run lint
+
+echo "Starting dev server and json-server in background..."
+
+# Start both servers in the background
+npm run dev &  
+DEV_PID=$!  
+
+npm run json-server &  
+JSON_SERVER_PID=$!  
+
+# Wait for servers to be ready (modify this according to your needs)
+echo "Waiting for servers to start..."
+sleep 5  
+
+# Run Playwright tests
+echo "Running Playwright tests..."
+npm run test  
+
+# Capture test exit code
+TEST_EXIT_CODE=$?  
+
+# Stop background processes
+kill -9 $DEV_PID
+kill -9 $JSON_SERVER_PID
+
+exit $TEST_EXIT_CODE
